name: llama-factory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - "vllm>=0.10.0,<0.10.2"
      - "flash-attn"
      - "deepspeed==0.16.8"
      - "lighteval[vllm,extended_tasks,math,dev]"
